
export const Baba = require('../../assets/baba.jpg')
export const Bebe = require('../../assets/bebe.jpg')
export const Carro = require('../../assets/carro.jpg')
export const Eletricista = require('../../assets/eletricista.jpg')
export const Emerson = require('../../assets/emerson.jpg')
export const Joao = require('../../assets/joao.jpg')
export const Logo = require('../../assets/logo.png')
export const Perfil = require('../../assets/perfil.jpg')
export const Predio = require('../../assets/predio.jpg')
export const Splash = require('../../assets/splash.png')
export const Zuleika = require('../../assets/zuleika.jpg')